version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080